#!/bin/bash

trap ctrl_c INT

function ctrl_c() {
  exit 1
}

ansible_lint_present=true
yaml_lint_present=true
tflint_present=true

# Check if ansible-lint is installed
if ! command -v ansible-lint &> /dev/null
then
  echo "Could not find Ansible-Lint"
  ansible_lint_present=false
fi

# Check if yaml-lint is installed
if ! command -v yamllint &> /dev/null
then
  echo "Could not find Yamllint"
  yaml_lint_present=false
fi

# Check if tflint is installed
if ! command -v tflint &> /dev/null
then
  echo "Could not find TFlint"
  tflint_present=false
fi

# Check if there are any changes added to commit
changes=$(git diff --cached --name-status)
if [ "${#changes}" -eq "0" ]
then
  exit 0
fi

git_root=$(git rev-parse --show-toplevel)
current_dir=$(pwd)

overall_exit_code=0

# Run Ansible-lint
if $ansible_lint_present && ([[ $changes == *ansible/* ]])
then
  echo "Running Ansible-Lint..."
  cd $git_root/ansible/
  ansible-lint 2>/dev/null
  lint_exit_code=$?
  overall_exit_code=$(echo "ibase=2;obase=2;$((overall_exit_code+lint_exit_code))" | bc -l)
fi

# Since Ansible-Lint also executes Yamllint (but not on all files), only execute yamllint when Ansible-Lint did not
# detect any issues to avoid double hits
if [[ $overall_exit_code == 0 ]]
then
  # Run Yaml-lint
  if $yaml_lint_present && ([[ $changes == *ansible/* ]])
  then
    echo "Running Yamllint..."
    cd $git_root/ansible/
    yamllint . -f parsable
    lint_exit_code=$?
    overall_exit_code=$(echo "ibase=2;obase=2;$((overall_exit_code+lint_exit_code))" | bc -l)
  fi
fi

declare -a tf_projects=('container_registry' 'key_vault' 'service_principals')

# Run TF-Lint
for project in "${tf_projects[@]}"
do
  if $tflint_present && ([[ $changes == *terraform/$project/* ]])
  then
    echo "Running TF-Lint for '$project'..."
    cd $git_root/terraform/$project/
    tflint --init
    ./tf-exec lint
    lint_exit_code=$?
    overall_exit_code=$(echo "ibase=2;obase=2;$((overall_exit_code+lint_exit_code))" | bc -l)
  fi
done

[ $overall_exit_code -ne 0 ] && echo "Commit will be aborted. Fix linting issues first"
cd $current_dir

exit $overall_exit_code
