- hosts: networkhub
  roles:
  - role: ssh
  - role: common_tasks
  - role: common_tools
  - role: custom_tools
    install_tools:
    - dnsutils
  - role: dockerhost
  - role: rpi_monitor
  - role: static_ip
    static_ip: 192.168.100.251
    gateway: 192.168.100.1
    dns:
    - 127.0.0.1
    - 192.168.2.254
