- hosts: domotica
  roles:
  - role: ssh
  - role: common_tasks
  - role: common_tools
  - role: dockerhost
  - role: rpi_monitor
  - role: mount_usbdrive
    mount_device: sda
    mount_partition: sda1
