- hosts: pihole
  roles:
  - role: ssh
  - role: common_tasks
  - role: common_tools
  - role: dockerhost
  - role: rpi_monitor
  - role: static_ip
    static_ip: 192.168.2.10
    gateway: 192.168.2.254
    dns:
    - 127.0.0.1
    - "{{ gateway }}"
