- hosts: all
  tasks:
  - name: Install python-apt package
    apt:
      name: python-apt
      state: present
      update_cache: yes
    become: yes
    become_user: root

  - name: Run apt-get update
    apt:
      name: "*"
      autoremove: yes
      state: latest
      update_cache: yes
    become: yes
    become_user: root
