all:
  children:
    local:
      hosts:
        localhost:
          management_user: oscar
          ansible_connection: local
          ansible_python_interpreter: "{{ansible_playbook_python}}"
    network_nodes:
      hosts:
        pihole:
    dockerhosts:
      hosts:
        pihole:
        databaseserver:
        domotica:
    portainer_slaves:
      hosts:
        databaseserver:
        domotica:
    diun_nodes:
      hosts:
        pihole:
        databaseserver:
        domotica:
