all:
  children:
    local:
      hosts:
        localhost:
          management_user: oscar
          ansible_connection: local
          ansible_python_interpreter: "{{ansible_playbook_python}}"
    network_nodes:
      hosts:
        networkcontrol:
        networkhub:
    dockerhosts:
      hosts:
        networkcontrol:
        networkhub:
    portainer_slaves:
      hosts:
        networkhub:
    diun_nodes:
      hosts:
        networkhub:
        networkcontrol:
