- name: "Store the public key as authorized key"
  ansible.posix.authorized_key:
    user: "{{ management_user }}"
    key: "{{ ssh.public_key }}"
    state: present
  tags: [ssh]

- name: "Create group for SSH-users"
  group:
    name: ssh-users
  become: yes
  tags: [ssh]

- name: "Add management user to the 'ssh-users' group"
  user:
    name: "{{ management_user }}"
    append: yes
    groups: ssh-users
  become: yes
  tags: [ssh]

- name: "Set allowed groups for SSH access"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: AllowGroups ssh-users
    regexp: "^#?AllowGroups"
  become: yes
  notify: Restart sshd
  tags: [ssh]
