- name: Include vaulted variables
  include_vars: vault.yml
  tags: [docker-container]

- name: Login to Azure
  community.docker.docker_login:
    registry_url: "{{ container_registry.loginserver }}"
    username: "{{ container_registry.username }}"
    password: "{{ container_registry.password }}"
  tags: [docker-container, docker-login]

- name: Deploy Docker container
  include_role:
    name: dockercontainer
    tasks_from: default
  vars:
    container_basename: "dsmr-to-mqtt"
    container_image: "{{ container_registry.loginserver }}/dsmr-to-mqtt"
    container_tag: "{{ dsmr_to_mqtt.version }}"
    devices: "/dev/ttyUSB0"
    mounts:
    - { source: /etc/localtime, target: /etc/localtime, read_only: "yes", type: bind }
    - { source: /etc/timezone,  target: /etc/timezone,  read_only: "yes", type: bind }
    environment_variables:
      MQTT_USERNAME: "{{ dsmr_to_mqtt.mqtt_username }}"
      MQTT_PASSWORD: "{{ dsmr_to_mqtt.mqtt_password }}"
      MQTT_BROKER: "{{ dsmr_to_mqtt.mqtt_broker }}"
      TZ: "Europe/Amsterdam"
  tags: [docker-container]
